package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"
	"strconv"

	"github.com/golangLearning/gql/graph/model"
)

// UpsertCharacter is the resolver for the upsertCharacter field.
func (r *mutationResolver) UpsertCharacter(ctx context.Context, input model.CharacterInput) (*model.Character, error) {
	id := input.ID
	var character model.Character
	character.Name = input.Name
	character.CliqueType = input.CliqueType
	if input.IsHero != nil {
		character.IsHero = *input.IsHero
	}

	n := len(r.Resolver.CharacterStore)

	if n == 0 {
		r.Resolver.CharacterStore = make(map[string]model.Character)
	}

	if id != nil {
		cs, ok := r.Resolver.CharacterStore[*id]
		if !ok {
			return nil, fmt.Errorf("not found")
		}
		if input.IsHero == nil {
			character.IsHero = cs.IsHero
		}

		character.ID = *id
		r.Resolver.CharacterStore[*id] = character
	} else {
		// Generate new ID and object
		newID := strconv.Itoa(n + 1)
		character.ID = newID
		r.Resolver.CharacterStore[newID] = character
	}

	return &character, nil
}

// Character is the resolver for the character field.
func (r *queryResolver) Character(ctx context.Context, id string) (*model.Character, error) {
	character, ok := r.Resolver.CharacterStore[id]

	if !ok {
		return nil, fmt.Errorf("not found")
	}
	return &character, nil
}

// Characters is the resolver for the characters field.
func (r *queryResolver) Characters(ctx context.Context, cliqueType model.CliqueType) ([]*model.Character, error) {
	characters := make([]*model.Character, 0)
	for idx := range r.Resolver.CharacterStore {
		character := r.Resolver.CharacterStore[idx]
		if character.CliqueType == cliqueType {
			characters = append(characters, &character)
		}
	}

	return characters, nil
}

// CharactersList is the resolver for the charactersList field.
func (r *queryResolver) CharactersList(ctx context.Context) ([]*model.Character, error) {
	characters := make([]*model.Character, 0)
	for idx := range r.Resolver.CharacterStore {
		character := r.Resolver.CharacterStore[idx]
		characters = append(characters, &character)
	}

	return characters, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
